build:
	docker compose build

up:
	docker compose up -d

down:
	docker compose down

logs:
	docker compose logs -f

ps:
	docker compose ps

use-front:
	docker compose exec front-end sh

use-back:
	docker compose exec back-end bash
